import { Poppins } from "next/font/google";
import "../globals.css";
import dynamic from "next/dynamic";
import DashboardUiLayouts from "@/_layouts/mainDashbordUi/DashboardUiLayouts";
import AppContextProvider from "@/_contextApi/AppContext";
import ModelContextProvider from "@/_contextApi/ModelContextApi";
import ImgModelContextProvider from "@/_contextApi/ImgModelContextApi";
import Head from "next/head";
import FillterContextProvider from "@/_contextApi/FillterContextApi";
import CreateInputModel from "@/_components/models/CreateInputModel";
import { getUserAuthantication } from "../lib/authentication";
import AuthContextProvider from "@/_contextApi/authContext";
const DeleteModel = dynamic(() => import("@/_components/models/DeleteModel"), {
  ssr: false,
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  style: ["normal", "italic"],
  variable: "--font-poppins",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const userDetails = await getUserAuthantication();
  return (
    <html lang="en" className={` ${poppins.variable}`}>
      <head />
      <body>
        <AppContextProvider>
          <AuthContextProvider authData={userDetails}>
            <FillterContextProvider>
              <ModelContextProvider>
                <ImgModelContextProvider>
                  <DeleteModel />

                  <div>
                    <DashboardUiLayouts>{children}</DashboardUiLayouts>
                  </div>
                </ImgModelContextProvider>
              </ModelContextProvider>
            </FillterContextProvider>
          </AuthContextProvider>
        </AppContextProvider>
      </body>
    </html>
  );
}
