import localFont from "next/font/local";
import "../globals.css";
import dynamic from "next/dynamic";
import DashboardUiLayouts from "@/_layouts/mainDashbordUi/DashboardUiLayouts";
import AppContextProvider from "@/_contextApi/AppContext";
import ModelContextProvider from "@/_contextApi/ModelContextApi";
import ImgModelContextProvider from "@/_contextApi/ImgModelContextApi";
const DeleteModel = dynamic(() => import("@/_components/models/DeleteModel"), {
  ssr: false,
});
// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* <body className={`${geistSans.variable} ${geistMono.variable}`}> */}
      <body>
        <AppContextProvider>
          <ModelContextProvider>
            <ImgModelContextProvider>
              <DeleteModel />
              <div>
                <DashboardUiLayouts>{children}</DashboardUiLayouts>
              </div>
            </ImgModelContextProvider>
          </ModelContextProvider>
        </AppContextProvider>
      </body>
    </html>
  );
}
