import localFont from "next/font/local";
import { inter, roboto, poppins, montserrat } from "../fonts/fonts";
import "../globals.css";
import dynamic from "next/dynamic";
import DashboardUiLayouts from "@/_layouts/mainDashbordUi/DashboardUiLayouts";
import AppContextProvider from "@/_contextApi/AppContext";
import ModelContextProvider from "@/_contextApi/ModelContextApi";
import ImgModelContextProvider from "@/_contextApi/ImgModelContextApi";
const DeleteModel = dynamic(() => import("@/_components/models/DeleteModel"), {
  ssr: false,
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${roboto.variable} ${poppins.variable} ${montserrat.variable}`}
      >
        <AppContextProvider>
          <ModelContextProvider>
            <ImgModelContextProvider>
              <DeleteModel />
              <div>
                <DashboardUiLayouts>{children}</DashboardUiLayouts>
              </div>
            </ImgModelContextProvider>
          </ModelContextProvider>
        </AppContextProvider>
      </body>
    </html>
  );
}
